version: '3'
services:
  recipe-app-node:
    image: dannyjialiliu/codegram-api:latest
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNECTION_STRING = "mongodb+srv://codegram-admin:eEAKvPxSecdsb0oZ@us-west-2-free.0gxej4g.mongodb.net/UpdatesCollector?retryWrites=true&w=majority"
      - AUTH_SECRET_KEY="codegramOmegaSecretKey"
      - PSQL_CONNECTION_STRING="postgres://postgres:Peyman1380@localhost:5432/codegram"
      - GCLOUD_PROJECT_ID="codegram-393903"
      - GCLOUD_KEYFILE_PATH="./gcloudkey.json"
      - EMAIL_USER=kodygramme@gmail.com
      - EMAIL_PASSWORD=buaknommahtbfzpu
      - RECAPTCHA_SECRET_KEY="6Lev7GcnAAAAANyArOBrMtcITYF-O-6FzBOV-KNc"
    depends_on:
      - postgres

  recipe-app-client:
    image: dannyjialiliu/codegram-ui:latest
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: