name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd client
          npm ci
          cd ../backend
          npm ci

      - name: Build frontend
        run: cd client && npm run build

      - name: Build backend
        run: cd backend npm run build
