name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd client
          npm ci
          cd ../backend
          npm ci

      - name: Run frontend tests
        run: cd frontend && npm run test

      - name: Run backend tests
        run: cd backend && npm run test
